apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: otel-route
  namespace: opentelimetry
spec:
  parentRefs:
  - name: gateway
    namespace: opentelimetry
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /otel
    backendRefs:
    - name: opentelemetry-demo-frontendproxy
      port: 8080
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
  # ROUTE FOR NEXT.JS ASSETS
  - matches:
    - path:
        type: PathPrefix
        value: /_next
    backendRefs:
    - name: opentelemetry-demo-frontendproxy
      port: 8080
