apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otel-frontend-pdb
  namespace: opentelimetry
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otel-frontendproxy-pdb
  namespace: opentelimetry
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontendproxy
