apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: monitoring-routes
  namespace: monitoring
spec:
  parentRefs:
  - name: gateway
    namespace: opentelimetry
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /grafana
    backendRefs:
    - name: prometheus-stack-grafana
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /prometheus
    backendRefs:
    - name: prometheus-stack-kube-prom-prometheus
      port: 9090
  - matches:
    - path:
        type: PathPrefix
        value: /jaeger
    backendRefs:
    - name: jaeger
      port: 16686

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: logging-routes
  namespace: logging
spec:
  parentRefs:
  - name: gateway
    namespace: opentelimetry
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /kibana
    backendRefs:
    - name: kibana-kibana
      port: 5601
